/*
 * DonorVtables.h -Extern declarations for all donor vtable arrays
 * Generated: 2026-04-01 17:46:39
 * 303 donors
 *
 * DO NOT EDIT BY HAND. Regenerate with:
 *   python generate_donors.py <RelocateRVAs_output.txt>
 */

#ifndef CSF_DONOR_VTABLES_GENERATED_H
#define CSF_DONOR_VTABLES_GENERATED_H

#include <windows.h>

#define CSF_DONOR_COUNT 303

extern const UINT_PTR g_addLeechesStatusVtableRVAs[172];  /* AddLeechesStatus */
extern const UINT_PTR g_addStartingManaVtableRVAs[172];  /* AddStartingMana */
extern const UINT_PTR g_adrenalineVtableRVAs[172];  /* Adrenaline */
extern const UINT_PTR g_aIControlNextTurnVtableRVAs[172];  /* AIControlNextTurn */
extern const UINT_PTR g_allDamageCritsVtableRVAs[172];  /* AllDamageCrits */
extern const UINT_PTR g_allStatsUpVtableRVAs[172];  /* AllStatsUp */
extern const UINT_PTR g_allyInfestedVtableRVAs[172];  /* AllyInfested */
extern const UINT_PTR g_alphaCatVtableRVAs[172];  /* AlphaCat */
extern const UINT_PTR g_alphaTurnsVtableRVAs[172];  /* AlphaTurns */
extern const UINT_PTR g_ammoVtableRVAs[172];  /* Ammo */
extern const UINT_PTR g_applyStatusesNextTurnBeginVtableRVAs[172];  /* ApplyStatusesNextTurnBegin */
extern const UINT_PTR g_applyStatusesNextTurnEndVtableRVAs[172];  /* ApplyStatusesNextTurnEnd */
extern const UINT_PTR g_attractionVtableRVAs[172];  /* Attraction */
extern const UINT_PTR g_autoReanimateVtableRVAs[172];  /* AutoReanimate */
extern const UINT_PTR g_backflipWhenTargetedVtableRVAs[172];  /* BackflipWhenTargeted */
extern const UINT_PTR g_bleedVtableRVAs[172];  /* Bleed */
extern const UINT_PTR g_bleedThornsVtableRVAs[172];  /* BleedThorns */
extern const UINT_PTR g_blessingOfPeaceVtableRVAs[172];  /* BlessingOfPeace */
extern const UINT_PTR g_blindVtableRVAs[172];  /* Blind */
extern const UINT_PTR g_bloodzerkedVtableRVAs[172];  /* Bloodzerked */
extern const UINT_PTR g_blurVtableRVAs[172];  /* Blur */
extern const UINT_PTR g_bodyGuardVtableRVAs[172];  /* BodyGuard */
extern const UINT_PTR g_bombRatTurtleVtableRVAs[172];  /* BombRatTurtle */
extern const UINT_PTR g_boundVtableRVAs[172];  /* Bound */
extern const UINT_PTR g_bountyVtableRVAs[172];  /* Bounty */
extern const UINT_PTR g_braceVtableRVAs[172];  /* Brace */
extern const UINT_PTR g_brittleAllStatsUpVtableRVAs[172];  /* BrittleAllStatsUp */
extern const UINT_PTR g_brittleCharismaUpVtableRVAs[172];  /* BrittleCharismaUp */
extern const UINT_PTR g_brittleConstitutionUpVtableRVAs[172];  /* BrittleConstitutionUp */
extern const UINT_PTR g_brittleDexterityUpVtableRVAs[172];  /* BrittleDexterityUp */
extern const UINT_PTR g_brittleIntelligenceUpVtableRVAs[172];  /* BrittleIntelligenceUp */
extern const UINT_PTR g_brittleLuckUpVtableRVAs[172];  /* BrittleLuckUp */
extern const UINT_PTR g_brittleSpeedUpVtableRVAs[172];  /* BrittleSpeedUp */
extern const UINT_PTR g_brittleStatusBaseVtableRVAs[172];  /* BrittleStatusBase */
extern const UINT_PTR g_brittleStrengthUpVtableRVAs[172];  /* BrittleStrengthUp */
extern const UINT_PTR g_bruiseVtableRVAs[172];  /* Bruise */
extern const UINT_PTR g_burnVtableRVAs[172];  /* Burn */
extern const UINT_PTR g_capturedFamiliarIconVtableRVAs[172];  /* CapturedFamiliarIcon */
extern const UINT_PTR g_castAgainVtableRVAs[172];  /* CastAgain */
extern const UINT_PTR g_castAgainWithStatusVtableRVAs[172];  /* CastAgainWithStatus */
extern const UINT_PTR g_catPartsSizeScaleStatusVtableRVAs[172];  /* CatPartsSizeScaleStatus */
extern const UINT_PTR g_championUpgradeNextMinionVtableRVAs[172];  /* ChampionUpgradeNextMinion */
extern const UINT_PTR g_chargeVtableRVAs[172];  /* Charge */
extern const UINT_PTR g_chargeFistsVtableRVAs[172];  /* ChargeFists */
extern const UINT_PTR g_charismaUpVtableRVAs[172];  /* CharismaUp */
extern const UINT_PTR g_charmedVtableRVAs[172];  /* Charmed */
extern const UINT_PTR g_confusionVtableRVAs[172];  /* Confusion */
extern const UINT_PTR g_conjureBonusAbilityVtableRVAs[172];  /* ConjureBonusAbility */
extern const UINT_PTR g_conjureSingleUseBonusAbilityVtableRVAs[172];  /* ConjureSingleUseBonusAbility */
extern const UINT_PTR g_constitutionUpVtableRVAs[172];  /* ConstitutionUp */
extern const UINT_PTR g_consumedVtableRVAs[172];  /* Consumed */
extern const UINT_PTR g_consumingVtableRVAs[172];  /* Consuming */
extern const UINT_PTR g_copiedSpellsVtableRVAs[172];  /* CopiedSpells */
extern const UINT_PTR g_corpseCounterVtableRVAs[172];  /* CorpseCounter */
extern const UINT_PTR g_counterNextAttacksVtableRVAs[172];  /* CounterNextAttacks */
extern const UINT_PTR g_counterspellVtableRVAs[172];  /* Counterspell */
extern const UINT_PTR g_critChanceUpVtableRVAs[172];  /* CritChanceUp */
extern const UINT_PTR g_currentWeaponAddElectricElementVtableRVAs[172];  /* CurrentWeaponAddElectricElement */
extern const UINT_PTR g_currentWeaponAddPoisonVtableRVAs[172];  /* CurrentWeaponAddPoison */
extern const UINT_PTR g_currentWeaponDamageUpVtableRVAs[172];  /* CurrentWeaponDamageUp */
extern const UINT_PTR g_cyborgTurnsVtableRVAs[172];  /* CyborgTurns */
extern const UINT_PTR g_damageUpVtableRVAs[172];  /* DamageUp */
extern const UINT_PTR g_dashFuryVtableRVAs[172];  /* DashFury */
extern const UINT_PTR g_deathwormUndergroundVtableRVAs[172];  /* DeathwormUnderground */
extern const UINT_PTR g_decoySwapperVtableRVAs[172];  /* DecoySwapper */
extern const UINT_PTR g_delayedPainVtableRVAs[172];  /* DelayedPain */
extern const UINT_PTR g_delayedStatusApplicationVtableRVAs[172];  /* DelayedStatusApplication */
extern const UINT_PTR g_delayedTriggerVtableRVAs[172];  /* DelayedTrigger */
extern const UINT_PTR g_demonicGlyphVtableRVAs[172];  /* DemonicGlyph */
extern const UINT_PTR g_demonicGlyph_BiteVtableRVAs[172];  /* DemonicGlyph_Bite */
extern const UINT_PTR g_demonicGlyph_BounceVtableRVAs[172];  /* DemonicGlyph_Bounce */
extern const UINT_PTR g_demonicGlyph_FireVtableRVAs[172];  /* DemonicGlyph_Fire */
extern const UINT_PTR g_demonicGlyph_MovementVtableRVAs[172];  /* DemonicGlyph_Movement */
extern const UINT_PTR g_demonicGlyph_SummonVtableRVAs[172];  /* DemonicGlyph_Summon */
extern const UINT_PTR g_dexterityUpVtableRVAs[172];  /* DexterityUp */
extern const UINT_PTR g_diminishingHealthRegenVtableRVAs[172];  /* DiminishingHealthRegen */
extern const UINT_PTR g_disableTrampleVtableRVAs[172];  /* DisableTrample */
extern const UINT_PTR g_disableWeaponVtableRVAs[172];  /* DisableWeapon */
extern const UINT_PTR g_disguisedVtableRVAs[172];  /* Disguised */
extern const UINT_PTR g_dodgeVtableRVAs[172];  /* Dodge */
extern const UINT_PTR g_dodgeChance_StatusVtableRVAs[172];  /* DodgeChance_Status */
extern const UINT_PTR g_doomedVtableRVAs[172];  /* Doomed */
extern const UINT_PTR g_doubleCastVtableRVAs[172];  /* DoubleCast */
extern const UINT_PTR g_doubleCastSpellVtableRVAs[172];  /* DoubleCastSpell */
extern const UINT_PTR g_doubleCastSpellsEachTurn_StatusVtableRVAs[172];  /* DoubleCastSpellsEachTurn_Status */
extern const UINT_PTR g_doubleCastSpellThisTurnVtableRVAs[172];  /* DoubleCastSpellThisTurn */
extern const UINT_PTR g_doubleLootVtableRVAs[172];  /* DoubleLoot */
extern const UINT_PTR g_dragVtableRVAs[172];  /* Drag */
extern const UINT_PTR g_drowsyVtableRVAs[172];  /* Drowsy */
extern const UINT_PTR g_dybbukManualExitTagVtableRVAs[172];  /* DybbukManualExitTag */
extern const UINT_PTR g_dybbukPossessedVtableRVAs[172];  /* DybbukPossessed */
extern const UINT_PTR g_eliteUpgradeNextMinionVtableRVAs[172];  /* EliteUpgradeNextMinion */
extern const UINT_PTR g_emptyMindVtableRVAs[172];  /* EmptyMind */
extern const UINT_PTR g_endTurnVtableRVAs[172];  /* EndTurn */
extern const UINT_PTR g_enrageVtableRVAs[172];  /* Enrage */
extern const UINT_PTR g_eventBountyVtableRVAs[172];  /* EventBounty */
extern const UINT_PTR g_exhaustionVtableRVAs[172];  /* Exhaustion */
extern const UINT_PTR g_existUntilIdleUpkeepVtableRVAs[172];  /* ExistUntilIdleUpkeep */
extern const UINT_PTR g_extraBasicAttacks_StatusVtableRVAs[172];  /* ExtraBasicAttacks_Status */
extern const UINT_PTR g_extraBasicMoves_StatusVtableRVAs[172];  /* ExtraBasicMoves_Status */
extern const UINT_PTR g_factionDisguiseVtableRVAs[172];  /* FactionDisguise */
extern const UINT_PTR g_fearVtableRVAs[172];  /* Fear */
extern const UINT_PTR g_finalBossHitCountdownVtableRVAs[172];  /* FinalBossHitCountdown */
extern const UINT_PTR g_finalBossHitCountdownBorisVtableRVAs[172];  /* FinalBossHitCountdownBoris */
extern const UINT_PTR g_finalBossHitCountdownExplosiveVtableRVAs[172];  /* FinalBossHitCountdownExplosive */
extern const UINT_PTR g_finalBossHitCountdownHolyVtableRVAs[172];  /* FinalBossHitCountdownHoly */
extern const UINT_PTR g_fireArmorVtableRVAs[172];  /* FireArmor */
extern const UINT_PTR g_fireArmor2VtableRVAs[172];  /* FireArmor2 */
extern const UINT_PTR g_floatingRockTrapVtableRVAs[172];  /* FloatingRockTrap */
extern const UINT_PTR g_freeSpellVtableRVAs[172];  /* FreeSpell */
extern const UINT_PTR g_freezeVtableRVAs[172];  /* Freeze */
extern const UINT_PTR g_furyVtableRVAs[172];  /* Fury */
extern const UINT_PTR g_gainDisorderFromPool_PostCastVtableRVAs[172];  /* GainDisorderFromPool_PostCast */
extern const UINT_PTR g_grappledVtableRVAs[172];  /* Grappled */
extern const UINT_PTR g_grapplingVtableRVAs[172];  /* Grappling */
extern const UINT_PTR g_halfBasicAttackDamageVtableRVAs[172];  /* HalfBasicAttackDamage */
extern const UINT_PTR g_healthRegenUpVtableRVAs[172];  /* HealthRegenUp */
extern const UINT_PTR g_heavierHitsVtableRVAs[172];  /* HeavierHits */
extern const UINT_PTR g_heavyHitsVtableRVAs[172];  /* HeavyHits */
extern const UINT_PTR g_hexVtableRVAs[172];  /* Hex */
extern const UINT_PTR g_hiddenDoomedVtableRVAs[172];  /* HiddenDoomed */
extern const UINT_PTR g_hideEquipmentVtableRVAs[172];  /* HideEquipment */
extern const UINT_PTR g_iceArmorVtableRVAs[172];  /* IceArmor */
extern const UINT_PTR g_imbueAttackPassiveVtableRVAs[172];  /* ImbueAttackPassive */
extern const UINT_PTR g_imbueAttackStatusVtableRVAs[172];  /* ImbueAttackStatus */
extern const UINT_PTR g_imbueBleedVtableRVAs[172];  /* ImbueBleed */
extern const UINT_PTR g_imbueKnockOutCoinVtableRVAs[172];  /* ImbueKnockOutCoin */
extern const UINT_PTR g_imbueManaLeechVtableRVAs[172];  /* ImbueManaLeech */
extern const UINT_PTR g_imbuePoisonVtableRVAs[172];  /* ImbuePoison */
extern const UINT_PTR g_imbueRandomStatDownVtableRVAs[172];  /* ImbueRandomStatDown */
extern const UINT_PTR g_imbueWeaknessVtableRVAs[172];  /* ImbueWeakness */
extern const UINT_PTR g_immobileVtableRVAs[172];  /* Immobile */
extern const UINT_PTR g_increaseCumulativeBlastDamageVtableRVAs[172];  /* IncreaseCumulativeBlastDamage */
extern const UINT_PTR g_infestedVtableRVAs[172];  /* Infested */
extern const UINT_PTR g_instantMaxHealthUpVtableRVAs[172];  /* InstantMaxHealthUp */
extern const UINT_PTR g_instantMaxManaUpVtableRVAs[172];  /* InstantMaxManaUp */
extern const UINT_PTR g_intelligenceUpVtableRVAs[172];  /* IntelligenceUp */
extern const UINT_PTR g_invulnerableVtableRVAs[172];  /* Invulnerable */
extern const UINT_PTR g_justInCaseTrampleVtableRVAs[172];  /* JustInCaseTrample */
extern const UINT_PTR g_killsToManaThisTurnVtableRVAs[172];  /* KillsToManaThisTurn */
extern const UINT_PTR g_killsToMeatAndHealthThisTurnVtableRVAs[172];  /* KillsToMeatAndHealthThisTurn */
extern const UINT_PTR g_kineticSpikesVtableRVAs[172];  /* KineticSpikes */
extern const UINT_PTR g_knockbackDamageImmuneUntilSettledVtableRVAs[172];  /* KnockbackDamageImmuneUntilSettled */
extern const UINT_PTR g_lateBloomerVtableRVAs[172];  /* LateBloomer */
extern const UINT_PTR g_lateStatusApplicationVtableRVAs[172];  /* LateStatusApplication */
extern const UINT_PTR g_launchOffScreenVtableRVAs[172];  /* LaunchOffScreen */
extern const UINT_PTR g_leaveBehindVtableRVAs[172];  /* LeaveBehind */
extern const UINT_PTR g_leaveBehindRockOnKnockbackVtableRVAs[172];  /* LeaveBehindRockOnKnockback */
extern const UINT_PTR g_leechesVtableRVAs[172];  /* Leeches */
extern const UINT_PTR g_lifestealVtableRVAs[172];  /* Lifesteal */
extern const UINT_PTR g_loseShieldNextTurnVtableRVAs[172];  /* LoseShieldNextTurn */
extern const UINT_PTR g_luckUpVtableRVAs[172];  /* LuckUp */
extern const UINT_PTR g_madnessVtableRVAs[172];  /* Madness */
extern const UINT_PTR g_madnessChanceOnTurnBeginVtableRVAs[172];  /* MadnessChanceOnTurnBegin */
extern const UINT_PTR g_magicWeaknessVtableRVAs[172];  /* MagicWeakness */
extern const UINT_PTR g_manaLeechesVtableRVAs[172];  /* ManaLeeches */
extern const UINT_PTR g_markedVtableRVAs[172];  /* Marked */
extern const UINT_PTR g_maxHPUpVtableRVAs[172];  /* MaxHPUp */
extern const UINT_PTR g_maxStartingManaVtableRVAs[172];  /* MaxStartingMana */
extern const UINT_PTR g_meatyVtableRVAs[172];  /* Meaty */
extern const UINT_PTR g_meleeRangeUpVtableRVAs[172];  /* MeleeRangeUp */
extern const UINT_PTR g_missChanceVtableRVAs[172];  /* MissChance */
extern const UINT_PTR g_movementUpVtableRVAs[172];  /* MovementUp */
extern const UINT_PTR g_moveQuiveredVtableRVAs[172];  /* MoveQuivered */
extern const UINT_PTR g_mutateAfterXTurnsVtableRVAs[172];  /* MutateAfterXTurns */
extern const UINT_PTR g_mutedVtableRVAs[172];  /* Muted */
extern const UINT_PTR g_nextAbilityHealsVtableRVAs[172];  /* NextAbilityHeals */
extern const UINT_PTR g_nextAbilityIncreaseRangeVtableRVAs[172];  /* NextAbilityIncreaseRange */
extern const UINT_PTR g_nextActionLuckUpVtableRVAs[172];  /* NextActionLuckUp */
extern const UINT_PTR g_nextAttackBonusRangeVtableRVAs[172];  /* NextAttackBonusRange */
extern const UINT_PTR g_nextAttackSpecialCritVtableRVAs[172];  /* NextAttackSpecialCrit */
extern const UINT_PTR g_nextBasicAttackCritsThisTurnVtableRVAs[172];  /* NextBasicAttackCritsThisTurn */
extern const UINT_PTR g_nextDamageCritsVtableRVAs[172];  /* NextDamageCrits */
extern const UINT_PTR g_nextDamageReduceAndHealAlliesVtableRVAs[172];  /* NextDamageReduceAndHealAllies */
extern const UINT_PTR g_nextDamageReduceAndPushbackVtableRVAs[172];  /* NextDamageReduceAndPushback */
extern const UINT_PTR g_nextDamageReduceThisTurnVtableRVAs[172];  /* NextDamageReduceThisTurn */
extern const UINT_PTR g_nextMoveRangeIncreaseVtableRVAs[172];  /* NextMoveRangeIncrease */
extern const UINT_PTR g_nextMoveTramplesVtableRVAs[172];  /* NextMoveTramples */
extern const UINT_PTR g_nextSpellHealEqualToManaVtableRVAs[172];  /* NextSpellHealEqualToMana */
extern const UINT_PTR g_nextTurnDoubleRangedDamageVtableRVAs[172];  /* NextTurnDoubleRangedDamage */
extern const UINT_PTR g_noHealthRegenVtableRVAs[172];  /* NoHealthRegen */
extern const UINT_PTR g_noManaRegenVtableRVAs[172];  /* NoManaRegen */
extern const UINT_PTR g_noStartingManaVtableRVAs[172];  /* NoStartingMana */
extern const UINT_PTR g_oldStealthVtableRVAs[172];  /* OldStealth */
extern const UINT_PTR g_oneUseSpellDamageUpVtableRVAs[172];  /* OneUseSpellDamageUp */
extern const UINT_PTR g_ostracizedVtableRVAs[172];  /* Ostracized */
extern const UINT_PTR g_permanentCharmVtableRVAs[172];  /* PermanentCharm */
extern const UINT_PTR g_permanentConfusionVtableRVAs[172];  /* PermanentConfusion */
extern const UINT_PTR g_permanentImmobileVtableRVAs[172];  /* PermanentImmobile */
extern const UINT_PTR g_permanentMadnessVtableRVAs[172];  /* PermanentMadness */
extern const UINT_PTR g_petrifyVtableRVAs[172];  /* Petrify */
extern const UINT_PTR g_petrifyCharmedVtableRVAs[172];  /* PetrifyCharmed */
extern const UINT_PTR g_poisonVtableRVAs[172];  /* Poison */
extern const UINT_PTR g_poisonLaceVtableRVAs[172];  /* PoisonLace */
extern const UINT_PTR g_poisonThornsVtableRVAs[172];  /* PoisonThorns */
extern const UINT_PTR g_possessedVtableRVAs[172];  /* Possessed */
extern const UINT_PTR g_preEmptiveCounterNextAttacksVtableRVAs[172];  /* PreEmptiveCounterNextAttacks */
extern const UINT_PTR g_probeCharmedVtableRVAs[172];  /* ProbeCharmed */
extern const UINT_PTR g_quiveredVtableRVAs[172];  /* Quivered */
extern const UINT_PTR g_rangeUpVtableRVAs[172];  /* RangeUp */
extern const UINT_PTR g_reduceVtableRVAs[172];  /* Reduce */
extern const UINT_PTR g_reduceManaCostVtableRVAs[172];  /* ReduceManaCost */
extern const UINT_PTR g_reduceManaCostExcludeBrainstormVtableRVAs[172];  /* ReduceManaCostExcludeBrainstorm */
extern const UINT_PTR g_reflectVtableRVAs[172];  /* Reflect */
extern const UINT_PTR g_replaceNextBasicMoveVtableRVAs[172];  /* ReplaceNextBasicMove */
extern const UINT_PTR g_reviveNextRoundVtableRVAs[172];  /* ReviveNextRound */
extern const UINT_PTR g_rotVtableRVAs[172];  /* Rot */
extern const UINT_PTR g_safeDoomedVtableRVAs[172];  /* SafeDoomed */
extern const UINT_PTR g_scrambledVtableRVAs[172];  /* Scrambled */
extern const UINT_PTR g_serratedClawsVtableRVAs[172];  /* SerratedClaws */
extern const UINT_PTR g_shootHereReceiverVtableRVAs[172];  /* ShootHereReceiver */
extern const UINT_PTR g_shortCircuitVtableRVAs[172];  /* ShortCircuit */
extern const UINT_PTR g_sizeScaleVtableRVAs[172];  /* SizeScale */
extern const UINT_PTR g_sizeScalePercentVtableRVAs[172];  /* SizeScalePercent */
extern const UINT_PTR g_skipNextTurnVtableRVAs[172];  /* SkipNextTurn */
extern const UINT_PTR g_sleepVtableRVAs[172];  /* Sleep */
extern const UINT_PTR g_sleepParalysisVtableRVAs[172];  /* SleepParalysis */
extern const UINT_PTR g_slowVtableRVAs[172];  /* Slow */
extern const UINT_PTR g_smellBloodVtableRVAs[172];  /* SmellBlood */
extern const UINT_PTR g_soulLinkVtableRVAs[172];  /* SoulLink */
extern const UINT_PTR g_specialFriendsLockAbilityVtableRVAs[172];  /* SpecialFriendsLockAbility */
extern const UINT_PTR g_speedUpVtableRVAs[172];  /* SpeedUp */
extern const UINT_PTR g_speedUp_WithoutInitiativeVtableRVAs[172];  /* SpeedUp_WithoutInitiative */
extern const UINT_PTR g_spellDamageUpVtableRVAs[172];  /* SpellDamageUp */
extern const UINT_PTR g_spellShieldVtableRVAs[172];  /* SpellShield */
extern const UINT_PTR g_spiderInfestedVtableRVAs[172];  /* SpiderInfested */
extern const UINT_PTR g_statBountyVtableRVAs[172];  /* StatBounty */
extern const UINT_PTR g_statusVtableRVAs[172];  /* Status */
extern const UINT_PTR g_statusAfterXStacksVtableRVAs[172];  /* StatusAfterXStacks */
extern const UINT_PTR g_statusAfterXTurnsVtableRVAs[172];  /* StatusAfterXTurns */
extern const UINT_PTR g_stealthVtableRVAs[172];  /* Stealth */
extern const UINT_PTR g_stealthCritChanceVtableRVAs[172];  /* StealthCritChance */
extern const UINT_PTR g_stealthUntilBasicAttackVtableRVAs[172];  /* StealthUntilBasicAttack */
extern const UINT_PTR g_stealTurnVtableRVAs[172];  /* StealTurn */
extern const UINT_PTR g_strengthUpVtableRVAs[172];  /* StrengthUp */
extern const UINT_PTR g_stunVtableRVAs[172];  /* Stun */
extern const UINT_PTR g_swapBackAtTurnEndVtableRVAs[172];  /* SwapBackAtTurnEnd */
extern const UINT_PTR g_switcherooVtableRVAs[172];  /* Switcheroo */
extern const UINT_PTR g_t2CopyCatInternalVtableRVAs[172];  /* T2CopyCatInternal */
extern const UINT_PTR g_takeBonusTurnWithAIControlVtableRVAs[172];  /* TakeBonusTurnWithAIControl */
extern const UINT_PTR g_takeBonusTurnWithStatusVtableRVAs[172];  /* TakeBonusTurnWithStatus */
extern const UINT_PTR g_tangledVtableRVAs[172];  /* Tangled */
extern const UINT_PTR g_tarredVtableRVAs[172];  /* Tarred */
extern const UINT_PTR g_tauntedVtableRVAs[172];  /* Taunted */
extern const UINT_PTR g_tauntingVtableRVAs[172];  /* Taunting */
extern const UINT_PTR g_teamBonusAbilityVtableRVAs[172];  /* TeamBonusAbility */
extern const UINT_PTR g_techVtableRVAs[172];  /* Tech */
extern const UINT_PTR g_teleportBackAtTurnEndVtableRVAs[172];  /* TeleportBackAtTurnEnd */
extern const UINT_PTR g_tempBackstabVtableRVAs[172];  /* TempBackstab */
extern const UINT_PTR g_tempBackstabBleedVtableRVAs[172];  /* TempBackstabBleed */
extern const UINT_PTR g_tempBackstabPiercingVtableRVAs[172];  /* TempBackstabPiercing */
extern const UINT_PTR g_tempBackstabPoisonVtableRVAs[172];  /* TempBackstabPoison */
extern const UINT_PTR g_tempBasicAttackBonusAOEVtableRVAs[172];  /* TempBasicAttackBonusAOE */
extern const UINT_PTR g_tempBonusKnockbackVtableRVAs[172];  /* TempBonusKnockback */
extern const UINT_PTR g_tempBonusKnockbackDamageVtableRVAs[172];  /* TempBonusKnockbackDamage */
extern const UINT_PTR g_tempCharmedVtableRVAs[172];  /* TempCharmed */
extern const UINT_PTR g_tempCounterAttackVtableRVAs[172];  /* TempCounterAttack */
extern const UINT_PTR g_tempCritChanceUpVtableRVAs[172];  /* TempCritChanceUp */
extern const UINT_PTR g_tempDamageUpVtableRVAs[172];  /* TempDamageUp */
extern const UINT_PTR g_tempDexterityUpVtableRVAs[172];  /* TempDexterityUp */
extern const UINT_PTR g_tempInitiativeChangeVtableRVAs[172];  /* TempInitiativeChange */
extern const UINT_PTR g_tempInjuryImmunityVtableRVAs[172];  /* TempInjuryImmunity */
extern const UINT_PTR g_tempLuckUpVtableRVAs[172];  /* TempLuckUp */
extern const UINT_PTR g_tempMadnessVtableRVAs[172];  /* TempMadness */
extern const UINT_PTR g_tempManaCostReductionVtableRVAs[172];  /* TempManaCostReduction */
extern const UINT_PTR g_tempMeleeRangeUpVtableRVAs[172];  /* TempMeleeRangeUp */
extern const UINT_PTR g_tempMovementVtableRVAs[172];  /* TempMovement */
extern const UINT_PTR g_tempNoManaRegenVtableRVAs[172];  /* TempNoManaRegen */
extern const UINT_PTR g_temporaryVtableRVAs[172];  /* Temporary */
extern const UINT_PTR g_tempPassiveUntilSettledVtableRVAs[172];  /* TempPassiveUntilSettled */
extern const UINT_PTR g_tempPassiveWhileHasStatusVtableRVAs[172];  /* TempPassiveWhileHasStatus */
extern const UINT_PTR g_tempPenetrateVtableRVAs[172];  /* TempPenetrate */
extern const UINT_PTR g_tempPreEmptiveCounterAttackVtableRVAs[172];  /* TempPreEmptiveCounterAttack */
extern const UINT_PTR g_tempRangeUpVtableRVAs[172];  /* TempRangeUp */
extern const UINT_PTR g_tempSpeedUpVtableRVAs[172];  /* TempSpeedUp */
extern const UINT_PTR g_tempSpellDamageUpVtableRVAs[172];  /* TempSpellDamageUp */
extern const UINT_PTR g_tempStrengthUpVtableRVAs[172];  /* TempStrengthUp */
extern const UINT_PTR g_tempTrampleUntilSettledVtableRVAs[172];  /* TempTrampleUntilSettled */
extern const UINT_PTR g_thornsVtableRVAs[172];  /* Thorns */
extern const UINT_PTR g_thornsDamageImmuneUntilSettledVtableRVAs[172];  /* ThornsDamageImmuneUntilSettled */
extern const UINT_PTR g_tileDamageImmuneUntilSettledVtableRVAs[172];  /* TileDamageImmuneUntilSettled */
extern const UINT_PTR g_tilesMovedToCritChanceVtableRVAs[172];  /* TilesMovedToCritChance */
extern const UINT_PTR g_tilesMovedToHealthVtableRVAs[172];  /* TilesMovedToHealth */
extern const UINT_PTR g_tilesMovedToManaVtableRVAs[172];  /* TilesMovedToMana */
extern const UINT_PTR g_tilesMovedToNeighborHealVtableRVAs[172];  /* TilesMovedToNeighborHeal */
extern const UINT_PTR g_tilesMovedToStrengthVtableRVAs[172];  /* TilesMovedToStrength */
extern const UINT_PTR g_timeDelayStatusApplicationVtableRVAs[172];  /* TimeDelayStatusApplication */
extern const UINT_PTR g_towerDefenseStatusVtableRVAs[172];  /* TowerDefenseStatus */
extern const UINT_PTR g_towerDefenseStatus2VtableRVAs[172];  /* TowerDefenseStatus2 */
extern const UINT_PTR g_trailBlazerVtableRVAs[172];  /* TrailBlazer */
extern const UINT_PTR g_trampleVtableRVAs[172];  /* Trample */
extern const UINT_PTR g_transformAfterXTurnsVtableRVAs[172];  /* TransformAfterXTurns */
extern const UINT_PTR g_transformBasicAttackVtableRVAs[172];  /* TransformBasicAttack */
extern const UINT_PTR g_transformBasicMoveVtableRVAs[172];  /* TransformBasicMove */
extern const UINT_PTR g_transformedAbilityVtableRVAs[172];  /* TransformedAbility */
extern const UINT_PTR g_transformInXTurnsVtableRVAs[172];  /* TransformInXTurns */
extern const UINT_PTR g_trapper_StatusVtableRVAs[172];  /* Trapper_Status */
extern const UINT_PTR g_twoThirdsBasicAttackDamageVtableRVAs[172];  /* TwoThirdsBasicAttackDamage */
extern const UINT_PTR g_visualCountDownThenApplyStatusVtableRVAs[172];  /* VisualCountDownThenApplyStatus */
extern const UINT_PTR g_weaknessVtableRVAs[172];  /* Weakness */
extern const UINT_PTR g_webbedVtableRVAs[172];  /* Webbed */
extern const UINT_PTR g_wetVtableRVAs[172];  /* Wet */
extern const UINT_PTR g_zombieVtableRVAs[172];  /* Zombie */

#endif /* CSF_DONOR_VTABLES_GENERATED_H */
